services:
  postgres:
    image: postgres:9.6.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=poc2fa
      - POSTGRES_PASSWORD=pocpass
      - POSTGRES_DB=twofactortest
      - POSTGRES_INITDB_ARGS=--encoding=utf8